// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.codeandmagic.protobuf2hibernate.sample;

public final class Descriptor_Dinosaur {
  private Descriptor_Dinosaur() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_Dinosaur_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_domain_Dinosaur_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016dinosaur.proto\022\006domain\"X\n\010Dinosaur\022\014\n\004" +
      "uuid\030\001 \002(\t\022\013\n\003age\030\002 \002(\003\022\014\n\004name\030\003 \002(\t\022\022\n" +
      "\ntailLength\030\004 \001(\002\022\017\n\007victims\030\005 \003(\tBE\n*or" +
      "g.codeandmagic.protobuf2hibernate.sample" +
      "B\023Descriptor_DinosaurH\001P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_domain_Dinosaur_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_domain_Dinosaur_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_domain_Dinosaur_descriptor,
              new java.lang.String[] { "Uuid", "Age", "Name", "TailLength", "Victims", },
              org.codeandmagic.protobuf2hibernate.sample.Dinosaur.class,
              org.codeandmagic.protobuf2hibernate.sample.Dinosaur.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
